# Generated by Django 2.2.1 on 2019-05-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lastname1', models.CharField(max_length=50)),
                ('lastname2', models.CharField(max_length=50)),
                ('party', models.CharField(max_length=60)),
                ('office', models.CharField(max_length=60)),
            ],
            options={
                'ordering': ['name', 'lastname1', 'lastname2'],
            },
        ),
        migrations.CreateModel(
            name='Elector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lastname1', models.CharField(max_length=50)),
                ('lastname2', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=100)),
                ('street_number', models.CharField(max_length=20)),
                ('neighbourhood', models.CharField(max_length=50)),
                ('county', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=1)),
                ('age', models.SmallIntegerField()),
            ],
            options={
                'ordering': ['name', 'lastname1', 'lastname2'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_candidate', models.CharField(max_length=50)),
                ('lastname1_candidatename_candidate', models.CharField(max_length=50)),
                ('lastname2_candidatename_candidate', models.CharField(max_length=50)),
                ('county', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=1)),
                ('age', models.SmallIntegerField()),
            ],
        ),
    ]
