# Generated by Django 2.2.1 on 2019-05-17 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv0t3', '0002_vote_date_emitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='elector',
            name='voted',
            field=models.BooleanField(default=False),
        ),
    ]
